[package]
name = "nyanpasu-ipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nyanpasu-utils = { workspace = true, features = ["core_manager"]}
tracing = { workspace = true }
tracing-attributes = { workspace = true }
tracing-futures = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["io-util"] }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
interprocess = { version = "2.2.0", features = ["tokio"] }
axum = { version = "0.7", features = ["ws"] }
axum-extra = { version = "0.9", features = ["typed-header"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["fs", "trace"] }
hyper = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
simd-json = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
pin-project-lite = "0.2.14"
tokio-tungstenite = "0.23" # Websocket impl
