[package]
name = "nyanpasu-service"
version = "0.1.0"
edition = "2021"
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
default-run = "nyanpasu-service"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
tokio = { workspace = true,  features = ["full"] }
nyanpasu-utils = { workspace = true, default-features = false, features = [
    "dirs",
] }
clap = { version = "4", features = ["derive"] }
thiserror.workspace = true
anyhow = { workspace = true }
tracing.workspace = true
tracing-appender.workspace = true
tracing-log.workspace = true
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "json",
    "parking_lot",
] }
tracing-attributes.workspace = true
service-manager = { git = "https://github.com/greenhat616/service-manager-rs.git" }
whoami = "1"
parking_lot = "0.12"
constcat = "0.5.0"

[target.'cfg(windows)'.dependencies]
check_elevation = "0.2.4"
windows-service = "0.7"
